pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                sh 'aws s3 cp --recursive  ${WORKSPACE}/S3-copy/html/ s3://test1ani-bucket/application/'
                sh 'aws s3 cp --recursive ${WORKSPACE}/S3-copy/images/ s3://test1ani-bucket/application/'
            }
        }
    }
}