pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                sh 'aws s3 cp -r ../html/ s3://test1ani-bucket/application/'
                sh 'aws s3 cp -r ../images/ s3://test1ani-bucket/application/'
            }
        }
    }
}